language: node_js
node_js:
  - 12

#services used in this ci-pipeline:
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed (install-phase)"

# Scripts to be run such as tests
before_script:
  - echo "no tests (before-script)"

script:
  # print the version for logging
  - docker --version 
  #building images:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api/udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api/udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  #tagging images to dockerhub:
  - docker tag reverseproxy khalid5165/reverseproxy
  - docker tag udagram-api-user khalid5165/udagram-api-user
  - docker tag udagram-api-feed khalid5165/udagram-api-feed
  - docker tag udagram-frontend khalid5165/udagram-frontend

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  #logging into dockerhub account to push the images:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #pushing all images into dockerhub repos:
  - docker push khalid5165/reverseproxy
  - docker push khalid5165/udagram-api-user
  - docker push khalid5165/udagram-api-feed
  - docker push khalid5165/udagram-frontend