apiVersion: v1
kind: Service
metadata:
  name: feed-app
  labels:
    run: feed-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: feed-app

---

apiVersion: v1
kind: Service
metadata:
  name: user-app
  labels:
    run: user-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: user-app

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    run: frontend-app
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    run: frontend-app

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy