#autoscale for feed:
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: feed-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feed-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65

---

#autoscale for user:
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65

---

#autoscale for frontend:
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-app
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65